version: 2.1

executors:
  go-executor:
    docker:
      - image: cimg/go:1.21  # Use a more recent Go version
    working_directory: /go/src/github.com/Silmi3607/invoicer-chapter2

jobs:
  build:
    executor: go-executor
    steps:
      - checkout
      - setup_remote_docker

      - run:
          name: Set up Go Modules
          command: |
            git config --global url."https://$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@github.com/".insteadOf "https://github.com/"
            go mod tidy
            go mod vendor

      - run:
          name: Run Tests
          command: |
            go test -v ./...

  deploy:
    executor: go-executor
    steps:
      - checkout
      - setup_remote_docker

      - run:
          name: Build Binary
          command: |
            go build -o bin/invoicer ./...

      - run:
          name: Authenticate Docker
          command: |
            echo "${DOCKER_PASS}" | docker login -u "${DOCKER_USER}" --password-stdin

      - run:
          name: Build Docker Image
          command: |
            docker build -t ${DOCKER_USER}/invoicer:${CIRCLE_SHA1} .
            docker tag ${DOCKER_USER}/invoicer:${CIRCLE_SHA1} ${DOCKER_USER}/invoicer:latest

      - run:
          name: Push Docker Image
          command: |
            docker push ${DOCKER_USER}/invoicer:${CIRCLE_SHA1}
            docker push ${DOCKER_USER}/invoicer:latest

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master
